version: '3.8'

services:
  web:
    build: .
    image: rohittt27/dockergithubactions:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - 8000:8000 