name: Django App CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    name: Deploy to Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and Push Docker Image
        run: |
          docker-compose build

          # Push the Docker image
          docker push rohittt27/dockergithubactions:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
